### ISSUE TITLE
Refaktorisera - lägg alla decoders i en annan fil

### ISSUE THREAD

**Issue by einarpersson** [Terebinthina/hw_decoder#2]
Du har massa logik som gör väldigt liknande saker
`meddelande -> decode -> resultat`

Jag skulle skapa en separat fil som heter `decoders.py` (och kanske döpa om huvudfilen till `main.py` bara för att tydliggöra skillnaden) och lägga alla decoding-funktioner där:

```
def dec_to_bin(msg):
    return bin(int(msg)).replace("0b", "")

def rogue_to_text(msg):
    ...
    return ...

```

På liknande sätt skulle jag skapa en till fil som heter `log.py` som hanterar allting som har att göra med loggning. Den kan exponera lämpliga funktioner som kallas från `main.py` när det behövs.

Vi vill åstadkomma något som kallas _Separation of concerns_

**Comment by Terebinthina** [comment]
#4 The issue has been resolved, however, some of the codecs have been shown to fail execution (2, 8, 9, 10 and the 11th). Further developing is required before resolving the main issue.
